name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install x11 deps
      run: sudo apt update && sudo apt install xorg-dev libxcb-shape0-dev libxcb-xfixes0-dev

    - uses: actions/checkout@v3
      with:
        repository: zee-editor/zee
    
    - run: cargo build --all-targets --all-features --release
      
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: zee
        path: target/release/zee
