name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:

    runs-on: ubuntu-latest
    container: clux/muslrust:stable

    steps:

    - run: apt update && apt install xorg-dev libxcb-shape0-dev libxcb-xfixes0-dev

    - uses: actions/checkout@v3
      with:
        repository: zee-editor/zee

    - run: ln -s /root/.cargo $HOME/.cargo
    - run: ln -s /root/.rustup $HOME/.rustup
    
    - uses: Swatinem/rust-cache@v1
      with:
        key: v2

#     - uses: actions-rs/cargo@v1
#       with:
#         command: build
#         args: --release

    - run: cargo build --all-features --release
      
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: zee
        path: target/release/zee
